### ISSUE TITLE
I have questions.

### ISSUE THREAD

**Issue by rfyo7243** [Melledy/SpiritWorker#1]
1. Can you make a guide to start server for SpiritWorker? and Database sql files.
2. How to connect client for SpiritWorker?
3. Can you upload all soulworker client files for SpiritWorker?

**Comment by Melledy** [comment]
I will be making a proper guide soon, for now:
**Prerequisites**: Mongodb (recommended 4.0+) and the GF soulworker client (1.7.20.2) installed 
1. Compile the server with `./gradlew jar`
2. Extract the .res files from data12.v in your soulworker client/data folder into a folder called `resources` in your spiritworker directory (use something like https://github.com/Leayal/VData-Reader)
3. Run the server with `java -jar spiritworker.jar`, you can also run both the auth and game servers separately by adding `-auth` or `-game` as an argument
4. You can run the client with `SoulWorker.exe --authCode aaaaa --ip 127.0.0.1 --port 9000`

**Comment by Melledy** [comment]
See [readme](https://github.com/Melledy/SpiritWorker/blob/master/README.md).
