### ISSUE TITLE
window immediately closes

### ISSUE THREAD

**Issue by oOBlackMasterOo** [Melledy/SpiritWorker#3]
which java version do I need to use when I create a new .bat the window immediately closes again "java -jar spiritworker.jar" this is command what i use for the server

and i have createt C:\Server\SpiritWorker\src\main\java\dev\spiritworker\resources data12.v files with .res are in folder

and i have java version jre1.8.0_231 and MongoDB latest version

**Comment by Melledy** [comment]
Yes, java 8 is the preferred java version. Try
```
java -jar spiritworker.jar
pause
```
in your bat file and show me the errors from that.

**Comment by oOBlackMasterOo** [comment]
C:\Server\SpiritWorker\src\main\java\dev\spiritworker>java -jar spiritworker.jar
Error: Unable to access jarfile spiritworker.jar

C:\Server\SpiritWorker\src\main\java\dev\spiritworker>pause

**Comment by Melledy** [comment]
You need to compile the server with `./gradlew.bat jar` first.

**Comment by oOBlackMasterOo** [comment]
it say build successful  https://ibb.co/m49rNBf

**Comment by Melledy** [comment]
Now try starting the server with your bat file. Make sure spiritworker.jar is in the same folder as the resources folder.

**Comment by oOBlackMasterOo** [comment]
it is only SpiritWorker.java and looks like this https://ibb.co/JK1vSqz Error: Unable to access jarfile spiritworker.jar I still get a message

**Comment by oOBlackMasterOo** [comment]
.gradle folder looks like this https://ibb.co/5spkKxG it says 6 files 18,1 KB (18.603 Bytes)

**Comment by Melledy** [comment]
The spiritworker.jar that is compiled should be your SpiritWorker/ directory

**Comment by oOBlackMasterOo** [comment]
she is not there my Java variable is  JAVA_HOME and C:\Program Files\Java\jre1.8.0_231 I think thats right

**Comment by Melledy** [comment]
Try running `./gradlew.bat jar` in your SpiritWorker folder again, if a `spiritworker.jar` file shows up, you've done it correctly.

**Comment by oOBlackMasterOo** [comment]
when i try to delete the folder .gradle and try to start gradlew.bat window comes to a second and ends 
and recreates .gradle folder new without the spiritworker.jar and when I try as an admin https://ibb.co/s20TWx4 I get the window

**Comment by oOBlackMasterOo** [comment]
java variable and look like that https://ibb.co/MNtNQt1 I do not know what the problem is, why he does not want to create the jar

**Comment by oOBlackMasterOo** [comment]
OK, it got to work
