### ISSUE TITLE
Look into this might help you

### ISSUE THREAD

**Issue by Sedurin** [Melledy/SpiritWorker#4]
You might wanna look into this 👍 

https://github.com/HoLLy-HaCKeR/SWSniff/issues/3

btw keep the good work up :^)

**Comment by MinusPL** [comment]
It will not :P
Author of this code has proper conversion for byte orders implemented, so no matter how it's stored it will be good.
Info from me: Max packet types: 65535, Max character amount on one server per account 255. max lvl possible to set 255, max servers 255.
