### ISSUE TITLE
Little info

### ISSUE THREAD

**Issue by MinusPL** [Melledy/SpiritWorker#7]
I've saw some packet definitions in your code.
I'm currently working too on some kind of emulator server, but written entirely in C++.

If I manage to find more about packets I will give you information, because two people might reconstruct these packets faster. :3

Also small info: That byte you have only guessed to be class advancement is actually it. If it is set to 1 (0x01) it will set you as advanced version of class. EVEN if you are below 55lvl. SO it's more like "flag".

So far I wasn't using your code to advance my own project, but I'd like to use your packet structures to progress better. That's why I ask for permission to do that.

**Comment by Melledy** [comment]
Thank you for the information about advancements and offering your help, there is also a discord at https://discord.gg/MqpbpkG where we discuss reverse engineering the game.

> So far I wasn't using your code to advance my own project, but I'd like to use your packet structures to progress better. That's why I ask for permission to do that.

Yes of course, you can use whatever see on this repo.

**Comment by Tomelyr** [comment]
Hey, could i get a new Discord Invite? the current one is now invalid

**Comment by Melledy** [comment]
https://discord.gg/jRZ83v
